name: Compile and Run lmtyn.h examples
on: [push, pull_request]

jobs:
  windows:
    strategy:
      matrix:
        cc: [gcc]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Compile lmtyn examples
        run: ${{ matrix.cc }} -s -O2 -mconsole -march=native -mtune=native -std=c89 -pedantic -nodefaultlibs -nostdlib -mno-stack-arg-probe -Xlinker /STACK:0x100000,0x100000 -fno-builtin -ffreestanding -fno-asynchronous-unwind-tables -fuse-ld=lld -Wall -Wextra -Werror -Wvla -Wconversion -Wdouble-promotion -Wmissing-field-initializers -Wno-uninitialized -Winit-self -Wunused -Wunused-macros -Wunused-local-typedefs examples/lmtyn_win32_nostdlib.c -o lmtyn_win32_nostdlib_${{ matrix.cc }}.exe -lkernel32
      - name: Run lmtyn examples
        run: .\lmtyn_win32_nostdlib_${{ matrix.cc }}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.cc }}-lmtyn_win32_nostdlib
          path: lmtyn_win32_nostdlib_${{ matrix.cc }}.exe
